/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class addedpostpanel extends javax.swing.JPanel {

    /**
     * Creates new form addedpostpanel
     */
    public addedpostpanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showaddedpostlb = new javax.swing.JLabel();
        showaddedcaptionlb = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(213, 150, 150));
        setLayout(null);

        showaddedpostlb.setText("showaddedpost");
        add(showaddedpostlb);
        showaddedpostlb.setBounds(20, 10, 440, 150);

        showaddedcaptionlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        showaddedcaptionlb.setText("showaddedcaption");
        add(showaddedcaptionlb);
        showaddedcaptionlb.setBounds(120, 180, 300, 30);

        deletebtn.setBackground(new java.awt.Color(255, 51, 51));
        deletebtn.setText("DELETE");
        add(deletebtn);
        deletebtn.setBounds(540, 10, 70, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton deletebtn;
    public javax.swing.JLabel showaddedcaptionlb;
    public javax.swing.JLabel showaddedpostlb;
    // End of variables declaration//GEN-END:variables
}
