/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class followingspanel extends javax.swing.JPanel {

    /**
     * Creates new form followingspanel
     */
    public followingspanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        followingimagelb = new javax.swing.JLabel();
        followingnamelb = new javax.swing.JLabel();
        unfollowbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(213, 150, 150));
        setLayout(null);

        followingimagelb.setText("followingimage");
        add(followingimagelb);
        followingimagelb.setBounds(10, 10, 180, 100);

        followingnamelb.setText("followingname");
        add(followingnamelb);
        followingnamelb.setBounds(230, 14, 150, 40);

        unfollowbtn.setBackground(new java.awt.Color(123, 156, 179));
        unfollowbtn.setText("unfollow");
        add(unfollowbtn);
        unfollowbtn.setBounds(413, 33, 100, 60);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel followingimagelb;
    public javax.swing.JLabel followingnamelb;
    public javax.swing.JButton unfollowbtn;
    // End of variables declaration//GEN-END:variables
}
