/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class followerspanel extends javax.swing.JPanel {

    /**
     * Creates new form followerspanel
     */
    public followerspanel() {
        initComponents();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        followerimagelb = new javax.swing.JLabel();
        followernamelb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(213, 150, 150));
        setLayout(null);

        followerimagelb.setText("followerimage");
        add(followerimagelb);
        followerimagelb.setBounds(20, 10, 210, 150);

        followernamelb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        followernamelb.setText("followername");
        add(followernamelb);
        followernamelb.setBounds(350, 50, 220, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel followerimagelb;
    public javax.swing.JLabel followernamelb;
    // End of variables declaration//GEN-END:variables
}
