
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 91987
 */
public class forgetpassword extends javax.swing.JFrame {

    // String name;
    String otp;
    String usernames;

    public forgetpassword() {
        initComponents();
        setSize(800, 700);
        forgetpasswordpanel2.setVisible(false);
        forgetpasswordpanel3.setVisible(false);
    }

    /* public forgetpassword(String username) {
        initComponents();
        setSize(800,700);
        name=username;
        forgetpasswordpanel2.setVisible(false);
        forgetpasswordpanel3.setVisible(false);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        forgetpasswordpanel1 = new javax.swing.JPanel();
        submitbtn = new javax.swing.JButton();
        usernamelb = new javax.swing.JLabel();
        usernametf = new javax.swing.JTextField();
        forgetpasswordpanel2 = new javax.swing.JPanel();
        otplb = new javax.swing.JLabel();
        otptf = new javax.swing.JTextField();
        submitbtn1 = new javax.swing.JButton();
        forgetpasswordpanel3 = new javax.swing.JPanel();
        usernamelb1 = new javax.swing.JLabel();
        newpasswordtf = new javax.swing.JTextField();
        confirmpasswordtf = new javax.swing.JTextField();
        usernamelb2 = new javax.swing.JLabel();
        changebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        forgetpasswordpanel1.setBackground(new java.awt.Color(123, 156, 179));
        forgetpasswordpanel1.setLayout(null);

        submitbtn.setBackground(new java.awt.Color(51, 255, 51));
        submitbtn.setText("SUBMIT");
        submitbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        forgetpasswordpanel1.add(submitbtn);
        submitbtn.setBounds(490, 40, 90, 30);

        usernamelb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernamelb.setText("username");
        forgetpasswordpanel1.add(usernamelb);
        usernamelb.setBounds(14, 34, 80, 30);

        usernametf.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        forgetpasswordpanel1.add(usernametf);
        usernametf.setBounds(149, 30, 200, 50);

        getContentPane().add(forgetpasswordpanel1);
        forgetpasswordpanel1.setBounds(30, 70, 620, 140);

        forgetpasswordpanel2.setBackground(new java.awt.Color(123, 156, 179));
        forgetpasswordpanel2.setLayout(null);

        otplb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        otplb.setText("OTP");
        forgetpasswordpanel2.add(otplb);
        otplb.setBounds(14, 34, 80, 30);

        otptf.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        forgetpasswordpanel2.add(otptf);
        otptf.setBounds(149, 30, 200, 50);

        submitbtn1.setBackground(new java.awt.Color(0, 255, 51));
        submitbtn1.setText("SUBMIT");
        submitbtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn1ActionPerformed(evt);
            }
        });
        forgetpasswordpanel2.add(submitbtn1);
        submitbtn1.setBounds(490, 40, 90, 30);

        getContentPane().add(forgetpasswordpanel2);
        forgetpasswordpanel2.setBounds(30, 230, 620, 150);

        forgetpasswordpanel3.setBackground(new java.awt.Color(123, 156, 179));
        forgetpasswordpanel3.setLayout(null);

        usernamelb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernamelb1.setText("CONFIRMPASSWORD");
        forgetpasswordpanel3.add(usernamelb1);
        usernamelb1.setBounds(20, 120, 160, 30);

        newpasswordtf.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        forgetpasswordpanel3.add(newpasswordtf);
        newpasswordtf.setBounds(220, 30, 200, 50);

        confirmpasswordtf.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        forgetpasswordpanel3.add(confirmpasswordtf);
        confirmpasswordtf.setBounds(220, 110, 200, 50);

        usernamelb2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        usernamelb2.setText("NEWPASSWORD");
        forgetpasswordpanel3.add(usernamelb2);
        usernamelb2.setBounds(20, 30, 120, 30);

        changebtn.setBackground(new java.awt.Color(0, 255, 51));
        changebtn.setText("CHANGE");
        changebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        forgetpasswordpanel3.add(changebtn);
        changebtn.setBounds(490, 80, 90, 30);

        getContentPane().add(forgetpasswordpanel3);
        forgetpasswordpanel3.setBounds(30, 400, 620, 190);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("FORGET PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
        // forgetpasswordpanel1.setVisible(false);
        //forgetpasswordpanel2.setVisible(true);
        try {
             usernames = usernametf.getText();
            
            if (usernames.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/forgetpassword1")
                        .queryString("username", usernames)
                        .asString();
                if (res.getStatus() == 200) {

                    String data = res.getBody();
                    StringTokenizer st = new StringTokenizer(data, ";#");
                    while (st.hasMoreTokens()) {
                        String ans = st.nextToken();
                        otp = st.nextToken();
                        System.out.println(otp);
                        if (ans.equals("success")) {
                            JOptionPane.showMessageDialog(this, "OTP is sent on your mobile no");
                            forgetpasswordpanel1.setVisible(false);
                            forgetpasswordpanel2.setVisible(true);

                        } else if (ans.equals("fail")) {
                            JOptionPane.showMessageDialog(this, "Incorrect Username");

                        }

                    }

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitbtnActionPerformed

    private void submitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn1ActionPerformed

        String enteredotp = otptf.getText();
        if (enteredotp.equals("")) {
            JOptionPane.showMessageDialog(this, "plz enter OTP");

        } else if (enteredotp.length() != 4) {

            JOptionPane.showMessageDialog(this, "Please enter 4 digit number");

        } else if (!enteredotp.contains(otp)) {

            JOptionPane.showMessageDialog(this, "Please enter correct values");

        } else {
            JOptionPane.showMessageDialog(this, "OTP  entered....THANKS!!");
            forgetpasswordpanel2.setVisible(false);
            forgetpasswordpanel1.setVisible(false);
            forgetpasswordpanel3.setVisible(true);

        }

    }//GEN-LAST:event_submitbtn1ActionPerformed

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed

        
        try {
            
            String newpassword = newpasswordtf.getText();
            String confirmpassword = confirmpasswordtf.getText();
            if ( newpassword.equals("") || confirmpassword.equals("")) {

                JOptionPane.showMessageDialog(this, "Please enter values/or fields are empty");

            } else if (!newpassword.equals(confirmpassword)) {
                JOptionPane.showMessageDialog(this, "new and confirm passwords should be same");
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/forgetpassword2")
                        .queryString("username", usernames)
                        .queryString("newpassword", newpassword)
                        .asString();
                if (res.getStatus() == 200) {
                    if (res.getBody().contentEquals("success")) {
                        JOptionPane.showMessageDialog(this, "passwordchange");
                        infernouserlogin ul = new infernouserlogin();
                        ul.setVisible(true);
                        dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Something invalid");
                    }
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_changebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgetpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changebtn;
    private javax.swing.JTextField confirmpasswordtf;
    private javax.swing.JPanel forgetpasswordpanel1;
    private javax.swing.JPanel forgetpasswordpanel2;
    private javax.swing.JPanel forgetpasswordpanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField newpasswordtf;
    private javax.swing.JLabel otplb;
    private javax.swing.JTextField otptf;
    private javax.swing.JButton submitbtn;
    private javax.swing.JButton submitbtn1;
    private javax.swing.JLabel usernamelb;
    private javax.swing.JLabel usernamelb1;
    private javax.swing.JLabel usernamelb2;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
