
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;import java.io.IOException;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class infernousersignupform extends javax.swing.JFrame {

   JFileChooser chooser;
   File f;
   BufferedImage img;
   
    
   
    public infernousersignupform() {
        chooser=new JFileChooser();
         
        initComponents();
        setSize(1000,700);
        //setExtendedState(infernousersignupform.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        unlb = new javax.swing.JLabel();
        untf = new javax.swing.JTextField();
        psslb = new javax.swing.JLabel();
        emllb = new javax.swing.JLabel();
        mnlb = new javax.swing.JLabel();
        uplb1 = new javax.swing.JLabel();
        emltf = new javax.swing.JTextField();
        mntf = new javax.swing.JTextField();
        sbmbtn = new javax.swing.JButton();
        pssjptg = new javax.swing.JPasswordField();
        gendlb = new javax.swing.JLabel();
        showuplb = new javax.swing.JLabel();
        gendcb = new javax.swing.JComboBox<>();
        upphotobtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SIGN UP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 10, 180, 30);

        unlb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        unlb.setForeground(new java.awt.Color(255, 255, 255));
        unlb.setText("Enter Username");
        getContentPane().add(unlb);
        unlb.setBounds(30, 80, 190, 30);

        untf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(untf);
        untf.setBounds(460, 70, 230, 30);

        psslb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        psslb.setForeground(new java.awt.Color(255, 255, 255));
        psslb.setText("Enter Password");
        getContentPane().add(psslb);
        psslb.setBounds(30, 130, 190, 30);

        emllb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        emllb.setForeground(new java.awt.Color(255, 255, 255));
        emllb.setText("Enter Email");
        getContentPane().add(emllb);
        emllb.setBounds(30, 180, 190, 30);

        mnlb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mnlb.setForeground(new java.awt.Color(255, 255, 255));
        mnlb.setText("Mobile Number");
        getContentPane().add(mnlb);
        mnlb.setBounds(30, 250, 190, 30);

        uplb1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        uplb1.setForeground(new java.awt.Color(255, 255, 255));
        uplb1.setText("Upload Photo");
        getContentPane().add(uplb1);
        uplb1.setBounds(30, 360, 200, 30);

        emltf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(emltf);
        emltf.setBounds(460, 170, 230, 28);

        mntf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(mntf);
        mntf.setBounds(460, 230, 230, 28);

        sbmbtn.setBackground(new java.awt.Color(204, 0, 51));
        sbmbtn.setText("SUBMIT");
        sbmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmbtnActionPerformed(evt);
            }
        });
        getContentPane().add(sbmbtn);
        sbmbtn.setBounds(290, 500, 140, 50);

        pssjptg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(pssjptg);
        pssjptg.setBounds(460, 120, 230, 30);

        gendlb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gendlb.setForeground(new java.awt.Color(255, 255, 255));
        gendlb.setText("Gender");
        getContentPane().add(gendlb);
        gendlb.setBounds(40, 300, 140, 20);

        showuplb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(showuplb);
        showuplb.setBounds(730, 220, 170, 150);

        gendcb.setBackground(new java.awt.Color(123, 156, 179));
        gendcb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gendcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "LGBTQ" }));
        getContentPane().add(gendcb);
        gendcb.setBounds(460, 290, 230, 20);

        upphotobtn.setBackground(new java.awt.Color(123, 156, 179));
        upphotobtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        upphotobtn.setText("choose");
        upphotobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upphotobtnActionPerformed(evt);
            }
        });
        getContentPane().add(upphotobtn);
        upphotobtn.setBounds(460, 350, 230, 31);

        backbtn.setBackground(new java.awt.Color(123, 156, 179));
        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(20, 580, 100, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcok/1507776.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 2000, 1110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmbtnActionPerformed
       try{
           String username =untf.getText();
           String password=pssjptg.getText();
           String email=emltf.getText();
           String mobileno=mntf.getText();
           String gender=(String) gendcb.getSelectedItem();
           
           if( username.equals("") || password.equals("") || email.equals("") || mobileno.equals("") ||gender.equals("")){
               
                JOptionPane.showMessageDialog(this, "Please enter values");
  
           
           } else if(f==null){
               
               
                JOptionPane.showMessageDialog(this, "Please choose file");
                
                
           } else if(mobileno.length() !=10) {
               
               
               JOptionPane.showMessageDialog(this, "Please enter 10 digit number");
               
               
           } else if(!email.contains("@") || !email.contains(".")){
               
               
                JOptionPane.showMessageDialog(this, "Please enter mail with @ or .");
                
                
           }else{
                
                 HttpResponse<String> res = Unirest.post("http://localhost:8999/usersignup")
                                        .queryString("username", username)
                                         .queryString("password", password)
                                         .queryString("email", email)
                                       .queryString("mobileno",mobileno)
                                       .queryString("gender",gender)
                                      .field("photo", f)
                                       .asString();
             if(res.getStatus()==200)
             {
                 if(res.getBody().contentEquals("success")){
                     
                      JOptionPane.showMessageDialog(this, "sign up successfull");
                     infernouserlogin iulog=new infernouserlogin();
                     iulog.setVisible(true);
                     iulog.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                     this.dispose();
                     
                     
                 }else{
                       JOptionPane.showMessageDialog(this, "username taken");
                 }
                 
                      
                 
             }
           
           }    
         } catch  (Exception e) {
           e.printStackTrace();
              } 
    }//GEN-LAST:event_sbmbtnActionPerformed

    private void upphotobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upphotobtnActionPerformed
       int t;
       t = chooser.showOpenDialog(this);
       if(t==JFileChooser.APPROVE_OPTION){
           f=chooser.getSelectedFile();
           try{
            img = ImageIO.read(f.getAbsoluteFile());
       Image img3 = img.getScaledInstance(showuplb.getWidth(), showuplb.getHeight(), Image.SCALE_SMOOTH);
            showuplb.setIcon(new ImageIcon(img3));}
           catch (Exception e){
                e.printStackTrace();
           }
       }
    }//GEN-LAST:event_upphotobtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
       newmainhome hm =new newmainhome();
       hm.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

     
    
    
    
    public static void main(String args[]) {
          
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infernousersignupform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel emllb;
    private javax.swing.JTextField emltf;
    private javax.swing.JComboBox<String> gendcb;
    private javax.swing.JLabel gendlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel mnlb;
    private javax.swing.JTextField mntf;
    private javax.swing.JPasswordField pssjptg;
    private javax.swing.JLabel psslb;
    private javax.swing.JButton sbmbtn;
    private javax.swing.JLabel showuplb;
    private javax.swing.JLabel unlb;
    private javax.swing.JTextField untf;
    private javax.swing.JLabel uplb1;
    private javax.swing.JButton upphotobtn;
    // End of variables declaration//GEN-END:variables
}
