/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class showcomments extends javax.swing.JPanel {

    /**
     * Creates new form showcomments
     */
    public showcomments() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bylb = new javax.swing.JLabel();
        commentlb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 153, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        bylb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bylb.setForeground(new java.awt.Color(51, 51, 51));
        add(bylb);
        bylb.setBounds(0, 150, 190, 40);

        commentlb.setBackground(new java.awt.Color(51, 51, 51));
        commentlb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        commentlb.setForeground(new java.awt.Color(255, 255, 255));
        add(commentlb);
        commentlb.setBounds(40, 24, 240, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel bylb;
    public javax.swing.JLabel commentlb;
    // End of variables declaration//GEN-END:variables
}
