/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class showwallpanel extends javax.swing.JPanel {

    /**
     * Creates new form showwallpanel
     */
    public showwallpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showwallphotolb = new javax.swing.JLabel();
        followedtolb = new javax.swing.JLabel();
        followedtonamelb = new javax.swing.JLabel();
        wallcaptionlb = new javax.swing.JLabel();
        walldatelb = new javax.swing.JLabel();
        likebtn = new javax.swing.JButton();
        likecountlb = new javax.swing.JLabel();
        commentbtn = new javax.swing.JButton();
        commenttf = new javax.swing.JTextField();
        kscrolpane = new javax.swing.JScrollPane();
        commentpanel = new javax.swing.JPanel();
        datelb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(null);

        showwallphotolb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        add(showwallphotolb);
        showwallphotolb.setBounds(280, 10, 590, 540);

        followedtolb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        add(followedtolb);
        followedtolb.setBounds(880, 80, 210, 140);

        followedtonamelb.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        followedtonamelb.setForeground(new java.awt.Color(255, 255, 255));
        followedtonamelb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        add(followedtonamelb);
        followedtonamelb.setBounds(920, 240, 140, 40);

        wallcaptionlb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        wallcaptionlb.setForeground(new java.awt.Color(255, 255, 255));
        wallcaptionlb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        add(wallcaptionlb);
        wallcaptionlb.setBounds(290, 570, 440, 40);
        add(walldatelb);
        walldatelb.setBounds(1024, 590, 90, 0);

        likebtn.setBackground(new java.awt.Color(123, 156, 179));
        likebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        likebtn.setText("like");
        likebtn.setBorder(null);
        add(likebtn);
        likebtn.setBounds(750, 570, 80, 40);

        likecountlb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        likecountlb.setForeground(new java.awt.Color(255, 255, 255));
        likecountlb.setText("count");
        add(likecountlb);
        likecountlb.setBounds(840, 580, 60, 30);

        commentbtn.setBackground(new java.awt.Color(0, 0, 0));
        commentbtn.setForeground(new java.awt.Color(255, 255, 255));
        commentbtn.setText("comment");
        commentbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        add(commentbtn);
        commentbtn.setBounds(180, 540, 90, 40);
        add(commenttf);
        commenttf.setBounds(10, 540, 160, 30);

        commentpanel.setBackground(new java.awt.Color(0, 0, 0));
        commentpanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        commentpanel.setLayout(null);
        kscrolpane.setViewportView(commentpanel);

        add(kscrolpane);
        kscrolpane.setBounds(10, 30, 250, 490);

        datelb.setForeground(new java.awt.Color(255, 255, 255));
        add(datelb);
        datelb.setBounds(10, 590, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcok/Blue-fire-wallpaper-HD-download-free.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(-6, 0, 1960, 980);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton commentbtn;
    public javax.swing.JPanel commentpanel;
    public javax.swing.JTextField commenttf;
    public javax.swing.JLabel datelb;
    public javax.swing.JLabel followedtolb;
    public javax.swing.JLabel followedtonamelb;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane kscrolpane;
    public javax.swing.JButton likebtn;
    public javax.swing.JLabel likecountlb;
    public javax.swing.JLabel showwallphotolb;
    public javax.swing.JLabel wallcaptionlb;
    public javax.swing.JLabel walldatelb;
    // End of variables declaration//GEN-END:variables
}
