
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

public class userchangepassword extends javax.swing.JFrame {

    String cpusername;

    public userchangepassword(String homeusername) {
        initComponents();
        setSize(700, 600);
        cpusername = homeusername;
        usernametf.setText(homeusername);
        usernametf.setEnabled(false);

    }

    public userchangepassword() {
        initComponents();
        setSize(700, 600);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernamelb = new javax.swing.JLabel();
        opasswordlb = new javax.swing.JLabel();
        npasswordlb = new javax.swing.JLabel();
        cpasswordlb = new javax.swing.JLabel();
        changebtn = new javax.swing.JButton();
        usernametf = new javax.swing.JTextField();
        opasswordtf = new javax.swing.JTextField();
        npasswordtf = new javax.swing.JTextField();
        cpasswordtf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("CHANGE PASSWORD");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 20, 460, 50);

        usernamelb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernamelb.setText("USERNAME");
        getContentPane().add(usernamelb);
        usernamelb.setBounds(20, 114, 150, 30);

        opasswordlb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        opasswordlb.setText("OLDPASSWORD");
        getContentPane().add(opasswordlb);
        opasswordlb.setBounds(20, 174, 140, 30);

        npasswordlb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        npasswordlb.setText("NEWPASSWORD");
        getContentPane().add(npasswordlb);
        npasswordlb.setBounds(20, 250, 150, 30);

        cpasswordlb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cpasswordlb.setText("CONFIRMPASSWORD");
        getContentPane().add(cpasswordlb);
        cpasswordlb.setBounds(20, 330, 190, 30);

        changebtn.setBackground(new java.awt.Color(123, 156, 179));
        changebtn.setText("CHANGE");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        getContentPane().add(changebtn);
        changebtn.setBounds(250, 473, 110, 60);

        usernametf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(usernametf);
        usernametf.setBounds(279, 120, 230, 30);

        opasswordtf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(opasswordtf);
        opasswordtf.setBounds(280, 180, 230, 30);

        npasswordtf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(npasswordtf);
        npasswordtf.setBounds(280, 250, 230, 30);

        cpasswordtf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(cpasswordtf);
        cpasswordtf.setBounds(280, 330, 230, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srcok/baby-blue-color-solid-background-1920x1080.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 0, 1958, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        try {
            String username = usernametf.getText();
           // System.out.println(username);
            String oldpassword = opasswordtf.getText();
            String newpassword = npasswordtf.getText();
            String confirmpassword = cpasswordtf.getText();
            if (username.equals("") || oldpassword.equals("") || newpassword.equals("") || confirmpassword.equals("")) {

                JOptionPane.showMessageDialog(this, "Please enter values/or fields are empty");

            } else if (!newpassword.equals(confirmpassword)) {
                JOptionPane.showMessageDialog(this, "new and confirm passwords should be same");
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/userchangepassword")
                        .queryString("username", username)
                        .queryString("oldpassword", oldpassword)
                        .queryString("newpassword", newpassword)
                        .asString();
                 if(res.getStatus()==200){
                     if(res.getBody().contentEquals("success")){
                         JOptionPane.showMessageDialog(this, "passwordchange");
                         //dispose();
                         infernouserlogin iul =new infernouserlogin();
                         iul.setVisible(true);
                         dispose();
                         
                         
                     }else{
                         JOptionPane.showMessageDialog(this, "oldpassword invalid");
                     }
                 }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_changebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userchangepassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userchangepassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changebtn;
    private javax.swing.JLabel cpasswordlb;
    private javax.swing.JTextField cpasswordtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel npasswordlb;
    private javax.swing.JTextField npasswordtf;
    private javax.swing.JLabel opasswordlb;
    private javax.swing.JTextField opasswordtf;
    private javax.swing.JLabel usernamelb;
    private javax.swing.JTextField usernametf;
    // End of variables declaration//GEN-END:variables
}
