/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 91987
 */
public class userpanel extends javax.swing.JPanel {

    /**
     * Creates new form userpanel
     */
    public userpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchphotolb = new javax.swing.JLabel();
        searchnamelb = new javax.swing.JLabel();
        followbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(128, 128, 128));
        setLayout(null);

        searchphotolb.setText("searchphotolb");
        add(searchphotolb);
        searchphotolb.setBounds(20, 10, 120, 100);

        searchnamelb.setText("searchnamelb");
        add(searchnamelb);
        searchnamelb.setBounds(160, 10, 120, 30);

        followbtn.setBackground(new java.awt.Color(123, 156, 179));
        followbtn.setText("follow");
        add(followbtn);
        followbtn.setBounds(350, 30, 90, 40);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton followbtn;
    public javax.swing.JLabel searchnamelb;
    public javax.swing.JLabel searchphotolb;
    // End of variables declaration//GEN-END:variables
}
